/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
/**
 *
 * @author Gerardo
 */
public class Catequista extends javax.swing.JPanel {

    /**
     * Creates new form Catequista
     */
    public Catequista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfIdentiCat = new javax.swing.JTextField();
        txfApeCat = new javax.swing.JTextField();
        txfTelCat = new javax.swing.JTextField();
        jcomGradoCat = new javax.swing.JComboBox<>();
        txfEdadCat = new javax.swing.JTextField();
        txfDireccionCat = new javax.swing.JTextField();
        txfNombreCat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txfBuscarIdenti = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtlCat = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnEliminarCat = new javax.swing.JButton();
        btnActualizarCat = new javax.swing.JButton();
        btnAgregarCat = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(150, 215, 244));

        txfIdentiCat.setBackground(new java.awt.Color(225, 255, 250));
        txfIdentiCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfIdentiCat.setForeground(new java.awt.Color(0, 32, 96));
        txfIdentiCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfIdentiCat.setText("Identificador");
        txfIdentiCat.setBorder(null);
        txfIdentiCat.setPreferredSize(new java.awt.Dimension(62, 25));

        txfApeCat.setBackground(new java.awt.Color(225, 255, 250));
        txfApeCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfApeCat.setForeground(new java.awt.Color(0, 32, 96));
        txfApeCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfApeCat.setText("Apellido completo");
        txfApeCat.setBorder(null);
        txfApeCat.setPreferredSize(new java.awt.Dimension(62, 25));

        txfTelCat.setBackground(new java.awt.Color(225, 255, 250));
        txfTelCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfTelCat.setForeground(new java.awt.Color(0, 32, 96));
        txfTelCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfTelCat.setText("Teléfono/Celular");
        txfTelCat.setBorder(null);
        txfTelCat.setPreferredSize(new java.awt.Dimension(62, 25));

        jcomGradoCat.setBackground(new java.awt.Color(225, 255, 250));
        jcomGradoCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcomGradoCat.setForeground(new java.awt.Color(0, 32, 96));
        jcomGradoCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        txfEdadCat.setBackground(new java.awt.Color(225, 255, 250));
        txfEdadCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfEdadCat.setForeground(new java.awt.Color(0, 32, 96));
        txfEdadCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEdadCat.setText("Edad");
        txfEdadCat.setBorder(null);
        txfEdadCat.setPreferredSize(new java.awt.Dimension(62, 25));

        txfDireccionCat.setBackground(new java.awt.Color(225, 255, 250));
        txfDireccionCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfDireccionCat.setForeground(new java.awt.Color(0, 32, 96));
        txfDireccionCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfDireccionCat.setText("Dirección");
        txfDireccionCat.setBorder(null);
        txfDireccionCat.setPreferredSize(new java.awt.Dimension(62, 25));

        txfNombreCat.setBackground(new java.awt.Color(225, 255, 250));
        txfNombreCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfNombreCat.setForeground(new java.awt.Color(0, 32, 96));
        txfNombreCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNombreCat.setText("Nombre completo");
        txfNombreCat.setBorder(null);
        txfNombreCat.setPreferredSize(new java.awt.Dimension(62, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfDireccionCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfTelCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfApeCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfIdentiCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcomGradoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txfEdadCat, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addComponent(txfNombreCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfIdentiCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(txfApeCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfTelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomGradoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEdadCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txfDireccionCat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 32, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACIÓN CATEQUISTAS");

        txfBuscarIdenti.setBackground(new java.awt.Color(225, 255, 250));
        txfBuscarIdenti.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfBuscarIdenti.setForeground(new java.awt.Color(0, 32, 96));
        txfBuscarIdenti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfBuscarIdenti.setText("Identificador");
        txfBuscarIdenti.setBorder(null);
        txfBuscarIdenti.setPreferredSize(new java.awt.Dimension(62, 25));

        btnBuscar.setBackground(new java.awt.Color(150, 215, 244));
        btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 32, 96));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setFocusable(false);
        btnBuscar.setPreferredSize(new java.awt.Dimension(45, 25));

        jPanel2.setBackground(new java.awt.Color(150, 215, 244));

        jtlCat.setBackground(new java.awt.Color(225, 255, 250));
        jtlCat.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtlCat.setForeground(new java.awt.Color(0, 32, 96));
        jtlCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtlCat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiar.setBackground(new java.awt.Color(150, 215, 244));
        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 32, 96));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setFocusable(false);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(45, 25));

        btnEliminarCat.setBackground(new java.awt.Color(150, 215, 244));
        btnEliminarCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminarCat.setForeground(new java.awt.Color(0, 32, 96));
        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.setBorder(null);
        btnEliminarCat.setFocusable(false);
        btnEliminarCat.setPreferredSize(new java.awt.Dimension(45, 25));

        btnActualizarCat.setBackground(new java.awt.Color(150, 215, 244));
        btnActualizarCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnActualizarCat.setForeground(new java.awt.Color(0, 32, 96));
        btnActualizarCat.setText("Actualizar");
        btnActualizarCat.setBorder(null);
        btnActualizarCat.setFocusable(false);
        btnActualizarCat.setPreferredSize(new java.awt.Dimension(45, 25));

        btnAgregarCat.setBackground(new java.awt.Color(150, 215, 244));
        btnAgregarCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarCat.setForeground(new java.awt.Color(0, 32, 96));
        btnAgregarCat.setText("Agregar");
        btnAgregarCat.setBorder(null);
        btnAgregarCat.setFocusable(false);
        btnAgregarCat.setPreferredSize(new java.awt.Dimension(45, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfBuscarIdenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfBuscarIdenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarCat;
    public javax.swing.JButton btnAgregarCat;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminarCat;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> jcomGradoCat;
    public javax.swing.JTable jtlCat;
    public javax.swing.JTextField txfApeCat;
    public javax.swing.JTextField txfBuscarIdenti;
    public javax.swing.JTextField txfDireccionCat;
    public javax.swing.JTextField txfEdadCat;
    public javax.swing.JTextField txfIdentiCat;
    public javax.swing.JTextField txfNombreCat;
    public javax.swing.JTextField txfTelCat;
    // End of variables declaration//GEN-END:variables
}
