/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gerardo
 */
public class Tutores extends javax.swing.JPanel {

    /**
     * Creates new form Tutores
     */
    public Tutores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txfBuscarIdenti = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtlAlumnos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txfIdentAlumno = new javax.swing.JTextField();
        txfNombreA = new javax.swing.JTextField();
        txfApeA = new javax.swing.JTextField();
        jcomGradoA = new javax.swing.JComboBox<>();
        txfApeA1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        txfApeA2 = new javax.swing.JTextField();
        btnEliminarA = new javax.swing.JButton();
        btnAgregarA = new javax.swing.JButton();
        btnActualizarA = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 32, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACIÓN TUTORES");

        btnLimpiar.setBackground(new java.awt.Color(150, 215, 244));
        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 32, 96));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/components/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setFocusable(false);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(45, 25));

        txfBuscarIdenti.setBackground(new java.awt.Color(225, 255, 250));
        txfBuscarIdenti.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfBuscarIdenti.setForeground(new java.awt.Color(0, 32, 96));
        txfBuscarIdenti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfBuscarIdenti.setText("Matrícula del alumno");
        txfBuscarIdenti.setBorder(null);
        txfBuscarIdenti.setPreferredSize(new java.awt.Dimension(62, 25));

        btnBuscar.setBackground(new java.awt.Color(150, 215, 244));
        btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 32, 96));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/components/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setFocusable(false);
        btnBuscar.setPreferredSize(new java.awt.Dimension(45, 25));

        jPanel2.setBackground(new java.awt.Color(150, 215, 244));

        jtlAlumnos.setBackground(new java.awt.Color(225, 255, 250));
        jtlAlumnos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtlAlumnos.setForeground(new java.awt.Color(0, 32, 96));
        jtlAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtlAlumnos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPanel1.setBackground(new java.awt.Color(150, 215, 244));

        txfIdentAlumno.setBackground(new java.awt.Color(225, 255, 250));
        txfIdentAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfIdentAlumno.setForeground(new java.awt.Color(0, 32, 96));
        txfIdentAlumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfIdentAlumno.setText("Nombre completo tutor");
        txfIdentAlumno.setBorder(null);
        txfIdentAlumno.setPreferredSize(new java.awt.Dimension(62, 25));

        txfNombreA.setBackground(new java.awt.Color(225, 255, 250));
        txfNombreA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfNombreA.setForeground(new java.awt.Color(0, 32, 96));
        txfNombreA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNombreA.setText("Apellido completo tutor");
        txfNombreA.setBorder(null);
        txfNombreA.setPreferredSize(new java.awt.Dimension(62, 25));

        txfApeA.setBackground(new java.awt.Color(225, 255, 250));
        txfApeA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfApeA.setForeground(new java.awt.Color(0, 32, 96));
        txfApeA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfApeA.setText("Parentezco");
        txfApeA.setBorder(null);
        txfApeA.setPreferredSize(new java.awt.Dimension(62, 25));

        jcomGradoA.setBackground(new java.awt.Color(225, 255, 250));
        jcomGradoA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcomGradoA.setForeground(new java.awt.Color(0, 32, 96));
        jcomGradoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        txfApeA1.setBackground(new java.awt.Color(225, 255, 250));
        txfApeA1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfApeA1.setForeground(new java.awt.Color(0, 32, 96));
        txfApeA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfApeA1.setText("Teléfono/celular");
        txfApeA1.setBorder(null);
        txfApeA1.setPreferredSize(new java.awt.Dimension(62, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 32, 96));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edad");

        jCheckBox1.setBackground(new java.awt.Color(150, 215, 244));
        jCheckBox1.setForeground(new java.awt.Color(0, 32, 96));
        jCheckBox1.setText("Casado(a)");

        jCheckBox2.setBackground(new java.awt.Color(150, 215, 244));
        jCheckBox2.setForeground(new java.awt.Color(0, 32, 96));
        jCheckBox2.setText("Viuda(o)");

        jCheckBox3.setBackground(new java.awt.Color(150, 215, 244));
        jCheckBox3.setForeground(new java.awt.Color(0, 32, 96));
        jCheckBox3.setText("Soltero(a)");

        txfApeA2.setBackground(new java.awt.Color(225, 255, 250));
        txfApeA2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txfApeA2.setForeground(new java.awt.Color(0, 32, 96));
        txfApeA2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfApeA2.setText("Ocupación");
        txfApeA2.setBorder(null);
        txfApeA2.setPreferredSize(new java.awt.Dimension(62, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBox3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfApeA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfApeA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfNombreA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfIdentAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcomGradoA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addComponent(txfApeA2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfIdentAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfApeA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfApeA2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txfApeA1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomGradoA))
                .addGap(22, 22, 22))
        );

        btnEliminarA.setBackground(new java.awt.Color(150, 215, 244));
        btnEliminarA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminarA.setForeground(new java.awt.Color(0, 32, 96));
        btnEliminarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/components/eliminar.png"))); // NOI18N
        btnEliminarA.setText("Eliminar");
        btnEliminarA.setBorder(null);
        btnEliminarA.setFocusable(false);
        btnEliminarA.setPreferredSize(new java.awt.Dimension(45, 25));

        btnAgregarA.setBackground(new java.awt.Color(150, 215, 244));
        btnAgregarA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarA.setForeground(new java.awt.Color(0, 32, 96));
        btnAgregarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/components/anadir.png"))); // NOI18N
        btnAgregarA.setText("Agregar");
        btnAgregarA.setBorder(null);
        btnAgregarA.setFocusable(false);
        btnAgregarA.setPreferredSize(new java.awt.Dimension(45, 25));

        btnActualizarA.setBackground(new java.awt.Color(150, 215, 244));
        btnActualizarA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnActualizarA.setForeground(new java.awt.Color(0, 32, 96));
        btnActualizarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/components/actualizar.png"))); // NOI18N
        btnActualizarA.setText("Actualizar");
        btnActualizarA.setBorder(null);
        btnActualizarA.setFocusable(false);
        btnActualizarA.setPreferredSize(new java.awt.Dimension(45, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarA, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txfBuscarIdenti, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfBuscarIdenti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarA;
    public javax.swing.JButton btnAgregarA;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminarA;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> jcomGradoA;
    public javax.swing.JTable jtlAlumnos;
    public javax.swing.JTextField txfApeA;
    public javax.swing.JTextField txfApeA1;
    public javax.swing.JTextField txfApeA2;
    public javax.swing.JTextField txfBuscarIdenti;
    public javax.swing.JTextField txfIdentAlumno;
    public javax.swing.JTextField txfNombreA;
    // End of variables declaration//GEN-END:variables
}
